
from classes.customerrors.customerror import CustomError


class InputException(CustomError): 
    pass